
package Scientific_Calc;

import java.awt.event.KeyEvent;

/**
 *
 * @author Navneet Sharma
 */
public class Scientific_Calc extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operation;
    private Object math;
    public Scientific_Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnClear2 = new javax.swing.JButton();
        BtnBackSpace = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnRoot = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        BtnSub = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        BtnMul = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        BtnDevide = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        BtnDecimal = new javax.swing.JButton();
        BtnPlusMinus = new javax.swing.JButton();
        BtnIsEqualsTo = new javax.swing.JButton();
        BtnLog = new javax.swing.JButton();
        BtnSin = new javax.swing.JButton();
        BtnCos = new javax.swing.JButton();
        BtnTan = new javax.swing.JButton();
        BtnPie = new javax.swing.JButton();
        BtnXY = new javax.swing.JButton();
        BtnXY2 = new javax.swing.JButton();
        BtnXY3 = new javax.swing.JButton();
        BtnRoundf = new javax.swing.JButton();
        BtnCbrt = new javax.swing.JButton();
        BtnBin = new javax.swing.JButton();
        BtnHex = new javax.swing.JButton();
        BtnOctal = new javax.swing.JButton();
        BtnNfact = new javax.swing.JButton();
        BtnLnx = new javax.swing.JButton();
        TextDisplay1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        BtnClear2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnClear2.setText("C");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BtnBackSpace.setFont(new java.awt.Font("Wingdings", 1, 12)); // NOI18N
        BtnBackSpace.setText("");
        BtnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackSpaceActionPerformed(evt);
            }
        });

        BtnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnClear.setText("C");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        BtnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnAdd.setText("+");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnRoot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnRoot.setText("√  ");
        BtnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRootActionPerformed(evt);
            }
        });

        Btn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        BtnSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSub.setText("-");
        BtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubActionPerformed(evt);
            }
        });

        Btn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        BtnMul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnMul.setText("*");
        BtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMulActionPerformed(evt);
            }
        });

        Btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        BtnDevide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnDevide.setText("/");
        BtnDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDevideActionPerformed(evt);
            }
        });

        Btn0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        BtnDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnDecimal.setText(".");
        BtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDecimalActionPerformed(evt);
            }
        });

        BtnPlusMinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnPlusMinus.setText("±");
        BtnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlusMinusActionPerformed(evt);
            }
        });

        BtnIsEqualsTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnIsEqualsTo.setText("=");
        BtnIsEqualsTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIsEqualsToActionPerformed(evt);
            }
        });

        BtnLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnLog.setText("log");
        BtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogActionPerformed(evt);
            }
        });

        BtnSin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSin.setText("sin");
        BtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSinActionPerformed(evt);
            }
        });

        BtnCos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCos.setText("cos");
        BtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCosActionPerformed(evt);
            }
        });

        BtnTan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTan.setText("tan");
        BtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTanActionPerformed(evt);
            }
        });

        BtnPie.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        BtnPie.setText("π");
        BtnPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPieActionPerformed(evt);
            }
        });

        BtnXY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXY.setText("x^y");
        BtnXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXYActionPerformed(evt);
            }
        });

        BtnXY2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXY2.setText("x^2");
        BtnXY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXY2ActionPerformed(evt);
            }
        });

        BtnXY3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXY3.setText("x^3");
        BtnXY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXY3ActionPerformed(evt);
            }
        });

        BtnRoundf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnRoundf.setText("round");
        BtnRoundf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRoundfActionPerformed(evt);
            }
        });

        BtnCbrt.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        BtnCbrt.setText("cbrt");
        BtnCbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCbrtActionPerformed(evt);
            }
        });

        BtnBin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBin.setText("bin");
        BtnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBinActionPerformed(evt);
            }
        });

        BtnHex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnHex.setText("hex");
        BtnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHexActionPerformed(evt);
            }
        });

        BtnOctal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnOctal.setText("octal");
        BtnOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOctalActionPerformed(evt);
            }
        });

        BtnNfact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNfact.setText("n!");
        BtnNfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNfactActionPerformed(evt);
            }
        });

        BtnLnx.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        BtnLnx.setText("lnx");
        BtnLnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLnxActionPerformed(evt);
            }
        });

        TextDisplay1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextDisplay1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDisplay1ActionPerformed(evt);
            }
        });
        TextDisplay1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDisplay1KeyTyped(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Scientific ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextDisplay1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIsEqualsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnTan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnXY2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnRoundf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnXY3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCbrt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnNfact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnOctal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnLnx, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnXY)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnBin))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnBin, BtnCbrt, BtnCos, BtnHex, BtnLnx, BtnLog, BtnNfact, BtnOctal, BtnPie, BtnRoundf, BtnSin, BtnTan, BtnXY, BtnXY2, BtnXY3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnXY2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnPie, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnIsEqualsTo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnNfact, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnLnx, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnXY3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnRoundf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnBin, BtnCbrt, BtnCos, BtnHex, BtnLnx, BtnLog, BtnNfact, BtnOctal, BtnPie, BtnRoundf, BtnSin, BtnTan, BtnXY, BtnXY2, BtnXY3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       this.setResizable(true);
       this.setSize(475, 390);
       TextDisplay1.setSize(446, 35);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.setResizable(true);
       this.setSize(240, 390);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.setResizable(true);
       this.setSize(240, 390);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        String iNum = TextDisplay1.getText() + Btn7.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        String iNum = TextDisplay1.getText() + Btn6.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn6ActionPerformed

    private void BtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubActionPerformed
        firstnum = Double.parseDouble(TextDisplay1.getText());
        TextDisplay1.setText(null);
        operation=("-");
    }//GEN-LAST:event_BtnSubActionPerformed

    private void BtnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRootActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.sqrt(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnRootActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        firstnum = Double.parseDouble(TextDisplay1.getText());
        TextDisplay1.setText(null);
        operation=("+");
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSinActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.sin(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnSinActionPerformed

    private void BtnXY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXY2ActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = (ops * ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnXY2ActionPerformed

    private void BtnHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHexActionPerformed
       int a = Integer.parseInt(TextDisplay1.getText());  // HEXADECIMAL
       TextDisplay1.setText(Integer.toString(a,16));
    }//GEN-LAST:event_BtnHexActionPerformed

    private void TextDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDisplay1ActionPerformed
        
    }//GEN-LAST:event_TextDisplay1ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        String iNum = TextDisplay1.getText() + Btn8.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        String iNum = TextDisplay1.getText() + Btn9.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        String iNum = TextDisplay1.getText() + Btn4.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        String iNum = TextDisplay1.getText() + Btn5.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
       String iNum = TextDisplay1.getText() + Btn1.getText();
       TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        String iNum = TextDisplay1.getText() + Btn2.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        String iNum = TextDisplay1.getText() + Btn3.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn3ActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        TextDisplay1.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackSpaceActionPerformed
        String B_space = null;
        
        if(TextDisplay1.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(TextDisplay1.getText());
            strB.deleteCharAt(TextDisplay1.getText().length() - 1);
            B_space = strB.toString();
            TextDisplay1.setText(B_space);
        }
    }//GEN-LAST:event_BtnBackSpaceActionPerformed

    private void BtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDecimalActionPerformed
        if (!TextDisplay1.getText().contains("."))
        {
            TextDisplay1.setText(TextDisplay1.getText() + BtnDecimal.getText());
        }
    }//GEN-LAST:event_BtnDecimalActionPerformed

    private void BtnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlusMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = ops * (-1);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnPlusMinusActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        String iNum = TextDisplay1.getText() + Btn0.getText();
        TextDisplay1.setText(iNum);
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.log(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnLogActionPerformed

    private void BtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCosActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.cos(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnCosActionPerformed

    private void BtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTanActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.tan(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnTanActionPerformed

    private void BtnPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPieActionPerformed
        double ops;
        ops = (3.1415926535897932384626433832795);
        TextDisplay1.setText(String.valueOf(ops));                                         
    }//GEN-LAST:event_BtnPieActionPerformed

    private void BtnXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXYActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.pow(ops, ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnXYActionPerformed

    private void BtnXY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXY3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = (ops * ops * ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnXY3ActionPerformed

    private void BtnRoundfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRoundfActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.round(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnRoundfActionPerformed

    private void BtnCbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCbrtActionPerformed
       double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.cbrt(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnCbrtActionPerformed

    private void BtnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBinActionPerformed
        int a = Integer.parseInt(TextDisplay1.getText());  // BINARY
        TextDisplay1.setText(Integer.toString(a,2));
    }//GEN-LAST:event_BtnBinActionPerformed

    private void TextDisplay1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDisplay1KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TextDisplay1KeyTyped

    private void BtnIsEqualsToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIsEqualsToActionPerformed
        String ans;
        secondnum = Double.parseDouble(TextDisplay1.getText());
        if (operation == "+")
        {
            result = firstnum + secondnum;
            ans =  String.format("%.2f", result);
            TextDisplay1.setText(ans);
        }
        
        else if (operation == "-")
        {
            result = firstnum - secondnum;
            ans =  String.format("%.2f", result);
            TextDisplay1.setText(ans);
        }
        
        else if (operation == "*")
        {
            result = firstnum * secondnum;
            ans =  String.format("%.2f", result);
            TextDisplay1.setText(ans);
        }
        
        else if (operation == "/")
        {
            result = firstnum / secondnum;
            ans =  String.format("%.2f", result);
            TextDisplay1.setText(ans);
        }
        
        else if (operation == "%")
        {
            result = firstnum % secondnum;
            ans =  String.format("%.2f", result);
            TextDisplay1.setText(ans);
        }
        
    }//GEN-LAST:event_BtnIsEqualsToActionPerformed

    private void BtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMulActionPerformed
        firstnum = Double.parseDouble(TextDisplay1.getText());
        TextDisplay1.setText(null);
        operation=("*");
    }//GEN-LAST:event_BtnMulActionPerformed

    private void BtnDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDevideActionPerformed
         firstnum = Double.parseDouble(TextDisplay1.getText());
        TextDisplay1.setText(null);
        operation=("/");
    }//GEN-LAST:event_BtnDevideActionPerformed

    private void BtnOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOctalActionPerformed
        int a = Integer.parseInt(TextDisplay1.getText());  // HEXADECIMAL
       TextDisplay1.setText(Integer.toString(a,8));
    }//GEN-LAST:event_BtnOctalActionPerformed

    private void BtnLnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLnxActionPerformed
        double ops = Double.parseDouble(String.valueOf(TextDisplay1.getText()));
        ops = Math.log10(ops);
        TextDisplay1.setText(String.valueOf(ops));
    }//GEN-LAST:event_BtnLnxActionPerformed

    private void BtnNfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNfactActionPerformed
        double ops = Double.parseDouble(TextDisplay1.getText());
        double fact = 1;
        while(ops != 0)
        {
            fact = fact * ops;
            ops--;
        }
        TextDisplay1.setText("");
        TextDisplay1.setText(TextDisplay1.getText()+fact);
    }//GEN-LAST:event_BtnNfactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnBackSpace;
    private javax.swing.JButton BtnBin;
    private javax.swing.JButton BtnCbrt;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnClear2;
    private javax.swing.JButton BtnCos;
    private javax.swing.JButton BtnDecimal;
    private javax.swing.JButton BtnDevide;
    private javax.swing.JButton BtnHex;
    private javax.swing.JButton BtnIsEqualsTo;
    private javax.swing.JButton BtnLnx;
    private javax.swing.JButton BtnLog;
    private javax.swing.JButton BtnMul;
    private javax.swing.JButton BtnNfact;
    private javax.swing.JButton BtnOctal;
    private javax.swing.JButton BtnPie;
    private javax.swing.JButton BtnPlusMinus;
    private javax.swing.JButton BtnRoot;
    private javax.swing.JButton BtnRoundf;
    private javax.swing.JButton BtnSin;
    private javax.swing.JButton BtnSub;
    private javax.swing.JButton BtnTan;
    private javax.swing.JButton BtnXY;
    private javax.swing.JButton BtnXY2;
    private javax.swing.JButton BtnXY3;
    private javax.swing.JTextField TextDisplay1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
